/* eslint-disable */
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import type { Formatters } from './i18n-types'

export const initFormatters: Formatters = {}
