/* eslint-disable */
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import type { BaseLocale, Locales } from './i18n-types'

export const baseLocale: BaseLocale = 'en'

export const locales: Locales[] = ['en', 'pt-BR']

export const isLocale = (locale: string): locale is Locales => {
	return locales.includes(locale as Locales)
}

export const loadLocale = async (locale: Locales): Promise<void> => {
	return import(`./locales/${locale}.json`)
}
