/* eslint-disable */
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales = 'en' | 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	game: {
		title: string
		ui: {
			health: string
			mana: string
			stamina: string
			level: string
			experience: string
			inventory: string
			equipment: string
			skills: string
			stats: string
			settings: string
			newGame: string
			continue: string
			load: string
			save: string
			quit: string
			pause: string
			resume: string
		}
		combat: {
			attack: string
			defend: string
			useSkill: string
			useItem: string
			flee: string
			victory: string
			defeat: string
			damage: string
			healing: string
			critical: string
			miss: string
			enemyDefeated: string
			gainedExperience: string
			levelUp: string
			youDealt: string
			youReceived: string
			youHealed: string
		}
		items: {
			weapon: string
			armor: string
			potion: string
			consumable: string
			key: string
			quest: string
			use: string
			equip: string
			unequip: string
			drop: string
			sell: string
			buy: string
		}
		stats: {
			strength: string
			dexterity: string
			intelligence: string
			vitality: string
			luck: string
			attack: string
			defense: string
			magicAttack: string
			magicDefense: string
			speed: string
			criticalRate: string
			evasion: string
		}
		messages: {
			welcome: string
			gameOver: string
			gameSaved: string
			gameLoaded: string
			itemObtained: string
			itemUsed: string
			cannotUseHere: string
			notEnoughGold: string
			inventoryFull: string
			confirmQuit: string
			yes: string
			no: string
		}
	}
}

export type TranslationFunctions = {
	game: {
		title: () => LocalizedString
		ui: {
			health: () => LocalizedString
			mana: () => LocalizedString
			stamina: () => LocalizedString
			level: () => LocalizedString
			experience: () => LocalizedString
			inventory: () => LocalizedString
			equipment: () => LocalizedString
			skills: () => LocalizedString
			stats: () => LocalizedString
			settings: () => LocalizedString
			newGame: () => LocalizedString
			continue: () => LocalizedString
			load: () => LocalizedString
			save: () => LocalizedString
			quit: () => LocalizedString
			pause: () => LocalizedString
			resume: () => LocalizedString
		}
		combat: {
			attack: () => LocalizedString
			defend: () => LocalizedString
			useSkill: () => LocalizedString
			useItem: () => LocalizedString
			flee: () => LocalizedString
			victory: () => LocalizedString
			defeat: () => LocalizedString
			damage: () => LocalizedString
			healing: () => LocalizedString
			critical: () => LocalizedString
			miss: () => LocalizedString
			enemyDefeated: () => LocalizedString
			gainedExperience: (arg: { exp: number | string }) => LocalizedString
			levelUp: () => LocalizedString
			youDealt: (arg: { damage: number | string }) => LocalizedString
			youReceived: (arg: { damage: number | string }) => LocalizedString
			youHealed: (arg: { amount: number | string }) => LocalizedString
		}
		items: {
			weapon: () => LocalizedString
			armor: () => LocalizedString
			potion: () => LocalizedString
			consumable: () => LocalizedString
			key: () => LocalizedString
			quest: () => LocalizedString
			use: () => LocalizedString
			equip: () => LocalizedString
			unequip: () => LocalizedString
			drop: () => LocalizedString
			sell: () => LocalizedString
			buy: () => LocalizedString
		}
		stats: {
			strength: () => LocalizedString
			dexterity: () => LocalizedString
			intelligence: () => LocalizedString
			vitality: () => LocalizedString
			luck: () => LocalizedString
			attack: () => LocalizedString
			defense: () => LocalizedString
			magicAttack: () => LocalizedString
			magicDefense: () => LocalizedString
			speed: () => LocalizedString
			criticalRate: () => LocalizedString
			evasion: () => LocalizedString
		}
		messages: {
			welcome: () => LocalizedString
			gameOver: () => LocalizedString
			gameSaved: () => LocalizedString
			gameLoaded: () => LocalizedString
			itemObtained: (arg: { item: string }) => LocalizedString
			itemUsed: (arg: { item: string }) => LocalizedString
			cannotUseHere: () => LocalizedString
			notEnoughGold: () => LocalizedString
			inventoryFull: () => LocalizedString
			confirmQuit: () => LocalizedString
			yes: () => LocalizedString
			no: () => LocalizedString
		}
	}
}

export type Formatters = {}
