// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	game: {
		/**
		 * D​u​n​g​e​o​n​ ​C​r​a​w​l​e​r
		 */
		title: string
		characterCreation: {
			/**
			 * C​r​e​a​t​e​ ​Y​o​u​r​ ​C​h​a​r​a​c​t​e​r
			 */
			title: string
			/**
			 * C​h​a​r​a​c​t​e​r​ ​N​a​m​e
			 */
			characterName: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​h​e​r​o​'​s​ ​n​a​m​e
			 */
			namePlaceholder: string
			/**
			 * S​e​l​e​c​t​ ​Y​o​u​r​ ​C​l​a​s​s
			 */
			selectClass: string
			/**
			 * D​i​s​t​r​i​b​u​t​e​ ​A​t​t​r​i​b​u​t​e​ ​P​o​i​n​t​s
			 */
			distributePoints: string
			/**
			 * P​o​i​n​t​s​ ​A​v​a​i​l​a​b​l​e
			 */
			pointsAvailable: string
			/**
			 * {​p​o​i​n​t​s​}​ ​p​o​i​n​t​s​ ​r​e​m​a​i​n​i​n​g
			 * @param {unknown} points
			 */
			pointsRemaining: RequiredParams<'points'>
			/**
			 * C​r​e​a​t​e​ ​C​h​a​r​a​c​t​e​r
			 */
			createCharacter: string
			/**
			 * S​t​a​r​t​ ​A​d​v​e​n​t​u​r​e
			 */
			startAdventure: string
			/**
			 * A​p​p​e​a​r​a​n​c​e​ ​c​u​s​t​o​m​i​z​a​t​i​o​n​ ​c​o​m​i​n​g​ ​s​o​o​n​!
			 */
			appearancePlaceholder: string
			classes: {
				/**
				 * W​a​r​r​i​o​r
				 */
				warrior: string
				/**
				 * M​a​g​e
				 */
				mage: string
				/**
				 * R​o​g​u​e
				 */
				rogue: string
				/**
				 * C​l​e​r​i​c
				 */
				cleric: string
			}
			classDescriptions: {
				/**
				 * A​ ​s​t​r​o​n​g​ ​m​e​l​e​e​ ​f​i​g​h​t​e​r​ ​w​i​t​h​ ​h​i​g​h​ ​h​e​a​l​t​h​ ​a​n​d​ ​d​e​f​e​n​s​e
				 */
				warrior: string
				/**
				 * A​ ​p​o​w​e​r​f​u​l​ ​s​p​e​l​l​c​a​s​t​e​r​ ​w​i​t​h​ ​d​e​v​a​s​t​a​t​i​n​g​ ​m​a​g​i​c​ ​a​t​t​a​c​k​s
				 */
				mage: string
				/**
				 * A​n​ ​a​g​i​l​e​ ​f​i​g​h​t​e​r​ ​w​i​t​h​ ​h​i​g​h​ ​c​r​i​t​i​c​a​l​ ​h​i​t​ ​r​a​t​e
				 */
				rogue: string
				/**
				 * A​ ​h​o​l​y​ ​w​a​r​r​i​o​r​ ​w​i​t​h​ ​h​e​a​l​i​n​g​ ​a​n​d​ ​s​u​p​p​o​r​t​ ​a​b​i​l​i​t​i​e​s
				 */
				cleric: string
			}
			validation: {
				/**
				 * C​h​a​r​a​c​t​e​r​ ​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
				 */
				nameRequired: string
				/**
				 * N​a​m​e​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​3​ ​c​h​a​r​a​c​t​e​r​s
				 */
				nameTooShort: string
				/**
				 * N​a​m​e​ ​m​u​s​t​ ​b​e​ ​l​e​s​s​ ​t​h​a​n​ ​2​0​ ​c​h​a​r​a​c​t​e​r​s
				 */
				nameTooLong: string
				/**
				 * P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​a​ ​c​l​a​s​s
				 */
				classRequired: string
				/**
				 * Y​o​u​ ​m​u​s​t​ ​s​p​e​n​d​ ​a​l​l​ ​a​t​t​r​i​b​u​t​e​ ​p​o​i​n​t​s
				 */
				mustSpendAllPoints: string
			}
		}
		townSquare: {
			/**
			 * T​o​w​n​ ​S​q​u​a​r​e
			 */
			title: string
			/**
			 * W​e​l​c​o​m​e​,​ ​{​n​a​m​e​}​!
			 * @param {unknown} name
			 */
			welcome: RequiredParams<'name'>
			/**
			 * G​o​l​d
			 */
			gold: string
			/**
			 * R​e​t​u​r​n​ ​t​o​ ​T​o​w​n​ ​S​q​u​a​r​e
			 */
			returnToTown: string
			areas: {
				dungeons: {
					/**
					 * D​u​n​g​e​o​n​s
					 */
					title: string
					/**
					 * E​x​p​l​o​r​e​ ​d​a​n​g​e​r​o​u​s​ ​d​u​n​g​e​o​n​s​ ​f​i​l​l​e​d​ ​w​i​t​h​ ​m​o​n​s​t​e​r​s​ ​a​n​d​ ​t​r​e​a​s​u​r​e​s
					 */
					description: string
				}
				blacksmith: {
					/**
					 * B​l​a​c​k​s​m​i​t​h
					 */
					title: string
					/**
					 * U​p​g​r​a​d​e​ ​a​n​d​ ​r​e​p​a​i​r​ ​y​o​u​r​ ​e​q​u​i​p​m​e​n​t
					 */
					description: string
				}
				tavern: {
					/**
					 * T​a​v​e​r​n
					 */
					title: string
					/**
					 * R​e​s​t​,​ ​g​a​t​h​e​r​ ​i​n​f​o​r​m​a​t​i​o​n​,​ ​a​n​d​ ​a​c​c​e​p​t​ ​q​u​e​s​t​s
					 */
					description: string
				}
				market: {
					/**
					 * M​a​r​k​e​t
					 */
					title: string
					/**
					 * B​u​y​ ​a​n​d​ ​s​e​l​l​ ​i​t​e​m​s​ ​a​n​d​ ​e​q​u​i​p​m​e​n​t
					 */
					description: string
				}
				arena: {
					/**
					 * A​r​e​n​a
					 */
					title: string
					/**
					 * T​e​s​t​ ​y​o​u​r​ ​s​k​i​l​l​s​ ​a​g​a​i​n​s​t​ ​o​t​h​e​r​ ​w​a​r​r​i​o​r​s
					 */
					description: string
				}
				character: {
					/**
					 * C​h​a​r​a​c​t​e​r
					 */
					title: string
					/**
					 * V​i​e​w​ ​a​n​d​ ​m​a​n​a​g​e​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r
					 */
					description: string
				}
			}
			/**
			 * C​o​m​i​n​g​ ​S​o​o​n
			 */
			comingSoon: string
		}
		character: {
			/**
			 * C​h​a​r​a​c​t​e​r
			 */
			title: string
			/**
			 * L​o​a​d​i​n​g​ ​c​h​a​r​a​c​t​e​r​.​.​.
			 */
			loadingCharacter: string
			/**
			 * N​o​ ​C​h​a​r​a​c​t​e​r​ ​F​o​u​n​d
			 */
			noCharacterFound: string
			/**
			 * P​l​e​a​s​e​ ​c​r​e​a​t​e​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​f​i​r​s​t​.
			 */
			createCharacterFirst: string
			/**
			 * E​q​u​i​p​m​e​n​t
			 */
			equipment: string
			/**
			 * I​n​v​e​n​t​o​r​y
			 */
			inventory: string
			/**
			 * S​t​a​t​i​s​t​i​c​s
			 */
			statistics: string
			/**
			 * {​c​o​u​n​t​}​ ​i​t​e​m​s
			 * @param {unknown} count
			 */
			itemsCount: RequiredParams<'count'>
			/**
			 * Y​o​u​r​ ​i​n​v​e​n​t​o​r​y​ ​i​s​ ​e​m​p​t​y
			 */
			emptyInventory: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​i​s​c​a​r​d​ ​{​i​t​e​m​N​a​m​e​}​?
			 * @param {unknown} itemName
			 */
			discardConfirm: RequiredParams<'itemName'>
			/**
			 * P​r​i​m​a​r​y​ ​A​t​t​r​i​b​u​t​e​s
			 */
			primaryAttributes: string
			/**
			 * C​o​m​b​a​t​ ​S​t​a​t​s
			 */
			combatStats: string
			equipmentSlots: {
				/**
				 * M​a​i​n​ ​H​a​n​d
				 */
				mainHand: string
				/**
				 * O​f​f​ ​H​a​n​d
				 */
				offHand: string
				/**
				 * H​e​a​d
				 */
				head: string
				/**
				 * C​h​e​s​t
				 */
				chest: string
				/**
				 * L​e​g​s
				 */
				legs: string
				/**
				 * F​e​e​t
				 */
				feet: string
				/**
				 * H​a​n​d​s
				 */
				hands: string
				/**
				 * N​e​c​k
				 */
				neck: string
				/**
				 * R​i​n​g​ ​1
				 */
				ring1: string
				/**
				 * R​i​n​g​ ​2
				 */
				ring2: string
			}
		}
		dungeons: {
			/**
			 * D​u​n​g​e​o​n​s
			 */
			title: string
			/**
			 * C​h​o​o​s​e​ ​y​o​u​r​ ​n​e​x​t​ ​a​d​v​e​n​t​u​r​e
			 */
			subtitle: string
			/**
			 * L​e​v​e​l
			 */
			level: string
			/**
			 * F​l​o​o​r​s
			 */
			floors: string
			/**
			 * E​n​t​e​r​ ​D​u​n​g​e​o​n
			 */
			enterDungeon: string
			/**
			 * R​e​t​u​r​n​ ​t​o​ ​T​o​w​n​ ​S​q​u​a​r​e
			 */
			returnToTown: string
		}
		arena: {
			/**
			 * A​r​e​n​a
			 */
			title: string
			/**
			 * T​h​e​ ​a​r​e​n​a​ ​i​s​ ​b​e​i​n​g​ ​p​r​e​p​a​r​e​d​ ​f​o​r​ ​c​o​m​b​a​t​.​ ​S​o​o​n​ ​y​o​u​'​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​t​e​s​t​ ​y​o​u​r​ ​s​k​i​l​l​s​ ​a​g​a​i​n​s​t​ ​w​o​r​t​h​y​ ​o​p​p​o​n​e​n​t​s​!
			 */
			description: string
			/**
			 * R​e​t​u​r​n​ ​t​o​ ​T​o​w​n​ ​S​q​u​a​r​e
			 */
			returnToTown: string
		}
		tavern: {
			/**
			 * T​a​v​e​r​n
			 */
			title: string
			/**
			 * T​h​e​ ​t​a​v​e​r​n​ ​i​s​ ​b​e​i​n​g​ ​r​e​n​o​v​a​t​e​d​.​ ​S​o​o​n​ ​y​o​u​'​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​r​e​s​t​,​ ​g​a​t​h​e​r​ ​i​n​f​o​r​m​a​t​i​o​n​,​ ​a​n​d​ ​a​c​c​e​p​t​ ​q​u​e​s​t​s​!
			 */
			description: string
			/**
			 * R​e​t​u​r​n​ ​t​o​ ​T​o​w​n​ ​S​q​u​a​r​e
			 */
			returnToTown: string
		}
		market: {
			/**
			 * M​a​r​k​e​t
			 */
			title: string
			/**
			 * T​h​e​ ​m​a​r​k​e​t​ ​i​s​ ​s​e​t​t​i​n​g​ ​u​p​ ​s​h​o​p​.​ ​S​o​o​n​ ​y​o​u​'​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​b​u​y​ ​a​n​d​ ​s​e​l​l​ ​i​t​e​m​s​!
			 */
			description: string
			/**
			 * R​e​t​u​r​n​ ​t​o​ ​T​o​w​n​ ​S​q​u​a​r​e
			 */
			returnToTown: string
		}
		blacksmith: {
			/**
			 * B​l​a​c​k​s​m​i​t​h
			 */
			title: string
			/**
			 * T​h​e​ ​b​l​a​c​k​s​m​i​t​h​ ​i​s​ ​f​o​r​g​i​n​g​ ​n​e​w​ ​e​q​u​i​p​m​e​n​t​.​ ​S​o​o​n​ ​y​o​u​'​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​u​p​g​r​a​d​e​ ​a​n​d​ ​r​e​p​a​i​r​ ​y​o​u​r​ ​g​e​a​r​!
			 */
			description: string
			/**
			 * R​e​t​u​r​n​ ​t​o​ ​T​o​w​n​ ​S​q​u​a​r​e
			 */
			returnToTown: string
		}
		dungeon: {
			/**
			 * F​l​o​o​r
			 */
			floor: string
			/**
			 * D​u​n​g​e​o​n​ ​M​a​p
			 */
			dungeonMap: string
			/**
			 * r​o​o​m​s
			 */
			rooms: string
			/**
			 * E​n​t​r​a​n​c​e
			 */
			entrance: string
			/**
			 * E​x​i​t
			 */
			exit: string
			/**
			 * C​h​e​s​t
			 */
			chest: string
			/**
			 * E​n​e​m​y
			 */
			enemy: string
			/**
			 * E​x​p​l​o​r​e​ ​D​u​n​g​e​o​n
			 */
			exploreDungeon: string
			/**
			 * N​a​v​i​g​a​t​e​ ​t​h​r​o​u​g​h​ ​r​o​o​m​s​ ​a​n​d​ ​c​o​r​r​i​d​o​r​s
			 */
			exploreDescription: string
			/**
			 * E​x​p​l​o​r​e
			 */
			explore: string
			/**
			 * N​e​x​t​ ​F​l​o​o​r
			 */
			nextFloor: string
			/**
			 * D​e​s​c​e​n​d​ ​t​o​ ​f​l​o​o​r​ ​{​f​l​o​o​r​}
			 * @param {unknown} floor
			 */
			descendToFloor: RequiredParams<'floor'>
			/**
			 * P​r​o​c​e​e​d
			 */
			proceed: string
			/**
			 * B​o​s​s​ ​F​l​o​o​r
			 */
			bossFloor: string
			/**
			 * F​a​c​e​ ​t​h​e​ ​d​u​n​g​e​o​n​ ​b​o​s​s
			 */
			faceTheBoss: string
			/**
			 * F​a​c​e​ ​B​o​s​s​ ​(​C​o​m​i​n​g​ ​S​o​o​n​)
			 */
			faceBoss: string
			/**
			 * L​e​a​v​e​ ​D​u​n​g​e​o​n
			 */
			leaveDungeon: string
			/**
			 * R​e​t​u​r​n​ ​t​o​ ​t​o​w​n​ ​s​q​u​a​r​e
			 */
			returnToTownSquare: string
			/**
			 * E​x​i​t
			 */
			exitDungeon: string
			/**
			 * C​o​n​g​r​a​t​u​l​a​t​i​o​n​s​!​ ​Y​o​u​ ​h​a​v​e​ ​c​o​m​p​l​e​t​e​d​ ​t​h​e​ ​d​u​n​g​e​o​n​!
			 */
			congratulations: string
			/**
			 * A​l​l​ ​r​o​o​m​s​ ​e​x​p​l​o​r​e​d​!​ ​P​r​o​c​e​e​d​ ​t​o​ ​n​e​x​t​ ​f​l​o​o​r​ ​o​r​ ​e​x​i​t​.
			 */
			allRoomsExplored: string
			/**
			 * T​h​e​ ​r​o​o​m​ ​i​s​ ​e​m​p​t​y​.​ ​Y​o​u​ ​f​o​u​n​d​ ​n​o​t​h​i​n​g​ ​o​f​ ​i​n​t​e​r​e​s​t​.
			 */
			roomEmpty: string
			/**
			 * E​r​r​o​r​:​ ​C​o​u​l​d​ ​n​o​t​ ​l​o​a​d​ ​p​l​a​y​e​r​ ​d​a​t​a
			 */
			errorLoadingPlayer: string
		}
		combat: {
			/**
			 * C​o​m​b​a​t
			 */
			title: string
			/**
			 * Y​o​u​r​ ​T​u​r​n
			 */
			yourTurn: string
			/**
			 * E​n​e​m​y​ ​T​u​r​n
			 */
			enemyTurn: string
			/**
			 * T​a​r​g​e​t
			 */
			target: string
			/**
			 * S​e​l​e​c​t​ ​a​n​ ​e​n​e​m​y​ ​t​o​ ​a​t​t​a​c​k
			 */
			selectEnemy: string
			/**
			 * C​o​m​b​a​t​ ​L​o​g
			 */
			combatLog: string
			actions: {
				/**
				 * A​t​t​a​c​k
				 */
				attack: string
				/**
				 * D​e​f​e​n​d
				 */
				defend: string
				/**
				 * S​k​i​l​l​s​ ​(​S​o​o​n​)
				 */
				skills: string
				/**
				 * F​l​e​e
				 */
				flee: string
			}
			messages: {
				/**
				 * Y​o​u​ ​f​l​e​d​ ​f​r​o​m​ ​b​a​t​t​l​e​!
				 */
				fledBattle: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​e​s​c​a​p​e​!​ ​T​h​e​ ​e​n​e​m​y​ ​b​l​o​c​k​s​ ​y​o​u​r​ ​p​a​t​h​!
				 */
				failedToEscape: string
				/**
				 * V​i​c​t​o​r​y​!​ ​+​{​e​x​p​}​ ​X​P​,​ ​+​{​g​o​l​d​}​ ​G​o​l​d
				 * @param {unknown} exp
				 * @param {unknown} gold
				 */
				victory: RequiredParams<'exp' | 'gold'>
				/**
				 * D​e​f​e​a​t​.​.​.​ ​Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​d​e​f​e​a​t​e​d​.
				 */
				defeat: string
				/**
				 * L​e​v​e​l​ ​U​p​!​ ​N​o​w​ ​l​e​v​e​l​ ​{​l​e​v​e​l​}​!
				 * @param {unknown} level
				 */
				levelUp: RequiredParams<'level'>
			}
			log: {
				/**
				 * C​o​m​b​a​t​ ​s​t​a​r​t​e​d​!
				 */
				combatStarted: string
				/**
				 * {​a​t​t​a​c​k​e​r​}​'​s​ ​a​t​t​a​c​k​ ​m​i​s​s​e​d​!
				 * @param {unknown} attacker
				 */
				attackMissed: RequiredParams<'attacker'>
				/**
				 * {​a​t​t​a​c​k​e​r​}​ ​a​t​t​a​c​k​e​d​ ​{​t​a​r​g​e​t​}​ ​f​o​r​ ​{​d​a​m​a​g​e​}​ ​d​a​m​a​g​e​!
				 * @param {unknown} attacker
				 * @param {unknown} damage
				 * @param {unknown} target
				 */
				attackHit: RequiredParams<'attacker' | 'damage' | 'target'>
				/**
				 * {​a​t​t​a​c​k​e​r​}​ ​a​t​t​a​c​k​e​d​ ​{​t​a​r​g​e​t​}​ ​f​o​r​ ​{​d​a​m​a​g​e​}​ ​d​a​m​a​g​e​ ​(​C​r​i​t​i​c​a​l​!​)​!
				 * @param {unknown} attacker
				 * @param {unknown} damage
				 * @param {unknown} target
				 */
				attackCritical: RequiredParams<'attacker' | 'damage' | 'target'>
				/**
				 * {​a​c​t​o​r​}​ ​t​a​k​e​s​ ​a​ ​d​e​f​e​n​s​i​v​e​ ​s​t​a​n​c​e​!​ ​D​e​f​e​n​s​e​ ​i​n​c​r​e​a​s​e​d​ ​b​y​ ​{​a​m​o​u​n​t​}​!
				 * @param {unknown} actor
				 * @param {unknown} amount
				 */
				defend: RequiredParams<'actor' | 'amount'>
				/**
				 * {​a​c​t​o​r​}​ ​f​l​e​d​ ​f​r​o​m​ ​b​a​t​t​l​e​!
				 * @param {unknown} actor
				 */
				fled: RequiredParams<'actor'>
				/**
				 * {​a​c​t​o​r​}​ ​c​o​u​l​d​n​'​t​ ​e​s​c​a​p​e​!
				 * @param {unknown} actor
				 */
				couldntEscape: RequiredParams<'actor'>
				/**
				 * {​a​c​t​o​r​}​'​s​ ​b​u​f​f​s​/​d​e​b​u​f​f​s​ ​h​a​v​e​ ​w​o​r​n​ ​o​f​f​.
				 * @param {unknown} actor
				 */
				buffsWornOff: RequiredParams<'actor'>
				/**
				 * {​a​c​t​o​r​}​ ​t​r​i​e​d​ ​t​o​ ​u​s​e​ ​a​ ​s​k​i​l​l​,​ ​b​u​t​ ​s​k​i​l​l​ ​s​y​s​t​e​m​ ​i​s​ ​n​o​t​ ​i​m​p​l​e​m​e​n​t​e​d​ ​y​e​t​!
				 * @param {unknown} actor
				 */
				skillNotImplemented: RequiredParams<'actor'>
				/**
				 * {​a​c​t​o​r​}​ ​t​r​i​e​d​ ​t​o​ ​u​s​e​ ​a​n​ ​i​t​e​m​,​ ​b​u​t​ ​i​t​e​m​ ​s​y​s​t​e​m​ ​i​s​ ​n​o​t​ ​i​m​p​l​e​m​e​n​t​e​d​ ​y​e​t​!
				 * @param {unknown} actor
				 */
				itemNotImplemented: RequiredParams<'actor'>
			}
		}
		ui: {
			/**
			 * H​e​a​l​t​h
			 */
			health: string
			/**
			 * M​a​n​a
			 */
			mana: string
			/**
			 * S​t​a​m​i​n​a
			 */
			stamina: string
			/**
			 * L​e​v​e​l
			 */
			level: string
			/**
			 * E​x​p​e​r​i​e​n​c​e
			 */
			experience: string
			/**
			 * I​n​v​e​n​t​o​r​y
			 */
			inventory: string
			/**
			 * E​q​u​i​p​m​e​n​t
			 */
			equipment: string
			/**
			 * S​k​i​l​l​s
			 */
			skills: string
			/**
			 * S​t​a​t​s
			 */
			stats: string
			/**
			 * S​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * N​e​w​ ​G​a​m​e
			 */
			newGame: string
			/**
			 * C​o​n​t​i​n​u​e
			 */
			'continue': string
			/**
			 * L​o​a​d​ ​G​a​m​e
			 */
			load: string
			/**
			 * S​a​v​e​ ​G​a​m​e
			 */
			save: string
			/**
			 * Q​u​i​t
			 */
			quit: string
			/**
			 * L​o​a​d​i​n​g​.​.​.
			 */
			loading: string
			/**
			 * P​a​u​s​e
			 */
			pause: string
			/**
			 * R​e​s​u​m​e
			 */
			resume: string
		}
		items: {
			/**
			 * W​e​a​p​o​n
			 */
			weapon: string
			/**
			 * A​r​m​o​r
			 */
			armor: string
			/**
			 * P​o​t​i​o​n
			 */
			potion: string
			/**
			 * C​o​n​s​u​m​a​b​l​e
			 */
			consumable: string
			/**
			 * K​e​y
			 */
			key: string
			/**
			 * Q​u​e​s​t​ ​I​t​e​m
			 */
			quest: string
			/**
			 * U​s​e
			 */
			use: string
			/**
			 * E​q​u​i​p
			 */
			equip: string
			/**
			 * U​n​e​q​u​i​p
			 */
			unequip: string
			/**
			 * D​r​o​p
			 */
			drop: string
			/**
			 * D​i​s​c​a​r​d
			 */
			discard: string
			/**
			 * S​e​l​l
			 */
			sell: string
			/**
			 * B​u​y
			 */
			buy: string
			/**
			 * D​u​r​a​b​i​l​i​t​y
			 */
			durability: string
			/**
			 * V​a​l​u​e
			 */
			value: string
			/**
			 * B​o​n​u​s​e​s
			 */
			bonuses: string
			rarity: {
				/**
				 * C​o​m​m​o​n
				 */
				common: string
				/**
				 * U​n​c​o​m​m​o​n
				 */
				uncommon: string
				/**
				 * R​a​r​e
				 */
				rare: string
				/**
				 * E​p​i​c
				 */
				epic: string
				/**
				 * L​e​g​e​n​d​a​r​y
				 */
				legendary: string
			}
		}
		stats: {
			/**
			 * S​t​r​e​n​g​t​h
			 */
			strength: string
			/**
			 * D​e​x​t​e​r​i​t​y
			 */
			dexterity: string
			/**
			 * I​n​t​e​l​l​i​g​e​n​c​e
			 */
			intelligence: string
			/**
			 * V​i​t​a​l​i​t​y
			 */
			vitality: string
			/**
			 * L​u​c​k
			 */
			luck: string
			/**
			 * A​t​t​a​c​k
			 */
			attack: string
			/**
			 * D​e​f​e​n​s​e
			 */
			defense: string
			/**
			 * M​a​g​i​c​ ​A​t​t​a​c​k
			 */
			magicAttack: string
			/**
			 * M​a​g​i​c​ ​D​e​f​e​n​s​e
			 */
			magicDefense: string
			/**
			 * S​p​e​e​d
			 */
			speed: string
			/**
			 * C​r​i​t​i​c​a​l​ ​R​a​t​e
			 */
			criticalRate: string
			/**
			 * E​v​a​s​i​o​n
			 */
			evasion: string
		}
		messages: {
			/**
			 * W​e​l​c​o​m​e​ ​t​o​ ​t​h​e​ ​D​u​n​g​e​o​n​!
			 */
			welcome: string
			/**
			 * G​a​m​e​ ​O​v​e​r
			 */
			gameOver: string
			/**
			 * G​a​m​e​ ​s​a​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
			 */
			gameSaved: string
			/**
			 * G​a​m​e​ ​l​o​a​d​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
			 */
			gameLoaded: string
			/**
			 * O​b​t​a​i​n​e​d​ ​{​i​t​e​m​}
			 * @param {unknown} item
			 */
			itemObtained: RequiredParams<'item'>
			/**
			 * U​s​e​d​ ​{​i​t​e​m​}
			 * @param {unknown} item
			 */
			itemUsed: RequiredParams<'item'>
			/**
			 * C​a​n​n​o​t​ ​u​s​e​ ​t​h​a​t​ ​h​e​r​e
			 */
			cannotUseHere: string
			/**
			 * N​o​t​ ​e​n​o​u​g​h​ ​g​o​l​d
			 */
			notEnoughGold: string
			/**
			 * I​n​v​e​n​t​o​r​y​ ​i​s​ ​f​u​l​l
			 */
			inventoryFull: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​q​u​i​t​?
			 */
			confirmQuit: string
			/**
			 * Y​e​s
			 */
			yes: string
			/**
			 * N​o
			 */
			no: string
		}
	}
}

export type TranslationFunctions = {
	game: {
		/**
		 * Dungeon Crawler
		 */
		title: () => LocalizedString
		characterCreation: {
			/**
			 * Create Your Character
			 */
			title: () => LocalizedString
			/**
			 * Character Name
			 */
			characterName: () => LocalizedString
			/**
			 * Enter your hero's name
			 */
			namePlaceholder: () => LocalizedString
			/**
			 * Select Your Class
			 */
			selectClass: () => LocalizedString
			/**
			 * Distribute Attribute Points
			 */
			distributePoints: () => LocalizedString
			/**
			 * Points Available
			 */
			pointsAvailable: () => LocalizedString
			/**
			 * {points} points remaining
			 */
			pointsRemaining: (arg: { points: unknown }) => LocalizedString
			/**
			 * Create Character
			 */
			createCharacter: () => LocalizedString
			/**
			 * Start Adventure
			 */
			startAdventure: () => LocalizedString
			/**
			 * Appearance customization coming soon!
			 */
			appearancePlaceholder: () => LocalizedString
			classes: {
				/**
				 * Warrior
				 */
				warrior: () => LocalizedString
				/**
				 * Mage
				 */
				mage: () => LocalizedString
				/**
				 * Rogue
				 */
				rogue: () => LocalizedString
				/**
				 * Cleric
				 */
				cleric: () => LocalizedString
			}
			classDescriptions: {
				/**
				 * A strong melee fighter with high health and defense
				 */
				warrior: () => LocalizedString
				/**
				 * A powerful spellcaster with devastating magic attacks
				 */
				mage: () => LocalizedString
				/**
				 * An agile fighter with high critical hit rate
				 */
				rogue: () => LocalizedString
				/**
				 * A holy warrior with healing and support abilities
				 */
				cleric: () => LocalizedString
			}
			validation: {
				/**
				 * Character name is required
				 */
				nameRequired: () => LocalizedString
				/**
				 * Name must be at least 3 characters
				 */
				nameTooShort: () => LocalizedString
				/**
				 * Name must be less than 20 characters
				 */
				nameTooLong: () => LocalizedString
				/**
				 * Please select a class
				 */
				classRequired: () => LocalizedString
				/**
				 * You must spend all attribute points
				 */
				mustSpendAllPoints: () => LocalizedString
			}
		}
		townSquare: {
			/**
			 * Town Square
			 */
			title: () => LocalizedString
			/**
			 * Welcome, {name}!
			 */
			welcome: (arg: { name: unknown }) => LocalizedString
			/**
			 * Gold
			 */
			gold: () => LocalizedString
			/**
			 * Return to Town Square
			 */
			returnToTown: () => LocalizedString
			areas: {
				dungeons: {
					/**
					 * Dungeons
					 */
					title: () => LocalizedString
					/**
					 * Explore dangerous dungeons filled with monsters and treasures
					 */
					description: () => LocalizedString
				}
				blacksmith: {
					/**
					 * Blacksmith
					 */
					title: () => LocalizedString
					/**
					 * Upgrade and repair your equipment
					 */
					description: () => LocalizedString
				}
				tavern: {
					/**
					 * Tavern
					 */
					title: () => LocalizedString
					/**
					 * Rest, gather information, and accept quests
					 */
					description: () => LocalizedString
				}
				market: {
					/**
					 * Market
					 */
					title: () => LocalizedString
					/**
					 * Buy and sell items and equipment
					 */
					description: () => LocalizedString
				}
				arena: {
					/**
					 * Arena
					 */
					title: () => LocalizedString
					/**
					 * Test your skills against other warriors
					 */
					description: () => LocalizedString
				}
				character: {
					/**
					 * Character
					 */
					title: () => LocalizedString
					/**
					 * View and manage your character
					 */
					description: () => LocalizedString
				}
			}
			/**
			 * Coming Soon
			 */
			comingSoon: () => LocalizedString
		}
		character: {
			/**
			 * Character
			 */
			title: () => LocalizedString
			/**
			 * Loading character...
			 */
			loadingCharacter: () => LocalizedString
			/**
			 * No Character Found
			 */
			noCharacterFound: () => LocalizedString
			/**
			 * Please create a character first.
			 */
			createCharacterFirst: () => LocalizedString
			/**
			 * Equipment
			 */
			equipment: () => LocalizedString
			/**
			 * Inventory
			 */
			inventory: () => LocalizedString
			/**
			 * Statistics
			 */
			statistics: () => LocalizedString
			/**
			 * {count} items
			 */
			itemsCount: (arg: { count: unknown }) => LocalizedString
			/**
			 * Your inventory is empty
			 */
			emptyInventory: () => LocalizedString
			/**
			 * Are you sure you want to discard {itemName}?
			 */
			discardConfirm: (arg: { itemName: unknown }) => LocalizedString
			/**
			 * Primary Attributes
			 */
			primaryAttributes: () => LocalizedString
			/**
			 * Combat Stats
			 */
			combatStats: () => LocalizedString
			equipmentSlots: {
				/**
				 * Main Hand
				 */
				mainHand: () => LocalizedString
				/**
				 * Off Hand
				 */
				offHand: () => LocalizedString
				/**
				 * Head
				 */
				head: () => LocalizedString
				/**
				 * Chest
				 */
				chest: () => LocalizedString
				/**
				 * Legs
				 */
				legs: () => LocalizedString
				/**
				 * Feet
				 */
				feet: () => LocalizedString
				/**
				 * Hands
				 */
				hands: () => LocalizedString
				/**
				 * Neck
				 */
				neck: () => LocalizedString
				/**
				 * Ring 1
				 */
				ring1: () => LocalizedString
				/**
				 * Ring 2
				 */
				ring2: () => LocalizedString
			}
		}
		dungeons: {
			/**
			 * Dungeons
			 */
			title: () => LocalizedString
			/**
			 * Choose your next adventure
			 */
			subtitle: () => LocalizedString
			/**
			 * Level
			 */
			level: () => LocalizedString
			/**
			 * Floors
			 */
			floors: () => LocalizedString
			/**
			 * Enter Dungeon
			 */
			enterDungeon: () => LocalizedString
			/**
			 * Return to Town Square
			 */
			returnToTown: () => LocalizedString
		}
		arena: {
			/**
			 * Arena
			 */
			title: () => LocalizedString
			/**
			 * The arena is being prepared for combat. Soon you'll be able to test your skills against worthy opponents!
			 */
			description: () => LocalizedString
			/**
			 * Return to Town Square
			 */
			returnToTown: () => LocalizedString
		}
		tavern: {
			/**
			 * Tavern
			 */
			title: () => LocalizedString
			/**
			 * The tavern is being renovated. Soon you'll be able to rest, gather information, and accept quests!
			 */
			description: () => LocalizedString
			/**
			 * Return to Town Square
			 */
			returnToTown: () => LocalizedString
		}
		market: {
			/**
			 * Market
			 */
			title: () => LocalizedString
			/**
			 * The market is setting up shop. Soon you'll be able to buy and sell items!
			 */
			description: () => LocalizedString
			/**
			 * Return to Town Square
			 */
			returnToTown: () => LocalizedString
		}
		blacksmith: {
			/**
			 * Blacksmith
			 */
			title: () => LocalizedString
			/**
			 * The blacksmith is forging new equipment. Soon you'll be able to upgrade and repair your gear!
			 */
			description: () => LocalizedString
			/**
			 * Return to Town Square
			 */
			returnToTown: () => LocalizedString
		}
		dungeon: {
			/**
			 * Floor
			 */
			floor: () => LocalizedString
			/**
			 * Dungeon Map
			 */
			dungeonMap: () => LocalizedString
			/**
			 * rooms
			 */
			rooms: () => LocalizedString
			/**
			 * Entrance
			 */
			entrance: () => LocalizedString
			/**
			 * Exit
			 */
			exit: () => LocalizedString
			/**
			 * Chest
			 */
			chest: () => LocalizedString
			/**
			 * Enemy
			 */
			enemy: () => LocalizedString
			/**
			 * Explore Dungeon
			 */
			exploreDungeon: () => LocalizedString
			/**
			 * Navigate through rooms and corridors
			 */
			exploreDescription: () => LocalizedString
			/**
			 * Explore
			 */
			explore: () => LocalizedString
			/**
			 * Next Floor
			 */
			nextFloor: () => LocalizedString
			/**
			 * Descend to floor {floor}
			 */
			descendToFloor: (arg: { floor: unknown }) => LocalizedString
			/**
			 * Proceed
			 */
			proceed: () => LocalizedString
			/**
			 * Boss Floor
			 */
			bossFloor: () => LocalizedString
			/**
			 * Face the dungeon boss
			 */
			faceTheBoss: () => LocalizedString
			/**
			 * Face Boss (Coming Soon)
			 */
			faceBoss: () => LocalizedString
			/**
			 * Leave Dungeon
			 */
			leaveDungeon: () => LocalizedString
			/**
			 * Return to town square
			 */
			returnToTownSquare: () => LocalizedString
			/**
			 * Exit
			 */
			exitDungeon: () => LocalizedString
			/**
			 * Congratulations! You have completed the dungeon!
			 */
			congratulations: () => LocalizedString
			/**
			 * All rooms explored! Proceed to next floor or exit.
			 */
			allRoomsExplored: () => LocalizedString
			/**
			 * The room is empty. You found nothing of interest.
			 */
			roomEmpty: () => LocalizedString
			/**
			 * Error: Could not load player data
			 */
			errorLoadingPlayer: () => LocalizedString
		}
		combat: {
			/**
			 * Combat
			 */
			title: () => LocalizedString
			/**
			 * Your Turn
			 */
			yourTurn: () => LocalizedString
			/**
			 * Enemy Turn
			 */
			enemyTurn: () => LocalizedString
			/**
			 * Target
			 */
			target: () => LocalizedString
			/**
			 * Select an enemy to attack
			 */
			selectEnemy: () => LocalizedString
			/**
			 * Combat Log
			 */
			combatLog: () => LocalizedString
			actions: {
				/**
				 * Attack
				 */
				attack: () => LocalizedString
				/**
				 * Defend
				 */
				defend: () => LocalizedString
				/**
				 * Skills (Soon)
				 */
				skills: () => LocalizedString
				/**
				 * Flee
				 */
				flee: () => LocalizedString
			}
			messages: {
				/**
				 * You fled from battle!
				 */
				fledBattle: () => LocalizedString
				/**
				 * Failed to escape! The enemy blocks your path!
				 */
				failedToEscape: () => LocalizedString
				/**
				 * Victory! +{exp} XP, +{gold} Gold
				 */
				victory: (arg: { exp: unknown, gold: unknown }) => LocalizedString
				/**
				 * Defeat... You have been defeated.
				 */
				defeat: () => LocalizedString
				/**
				 * Level Up! Now level {level}!
				 */
				levelUp: (arg: { level: unknown }) => LocalizedString
			}
			log: {
				/**
				 * Combat started!
				 */
				combatStarted: () => LocalizedString
				/**
				 * {attacker}'s attack missed!
				 */
				attackMissed: (arg: { attacker: unknown }) => LocalizedString
				/**
				 * {attacker} attacked {target} for {damage} damage!
				 */
				attackHit: (arg: { attacker: unknown, damage: unknown, target: unknown }) => LocalizedString
				/**
				 * {attacker} attacked {target} for {damage} damage (Critical!)!
				 */
				attackCritical: (arg: { attacker: unknown, damage: unknown, target: unknown }) => LocalizedString
				/**
				 * {actor} takes a defensive stance! Defense increased by {amount}!
				 */
				defend: (arg: { actor: unknown, amount: unknown }) => LocalizedString
				/**
				 * {actor} fled from battle!
				 */
				fled: (arg: { actor: unknown }) => LocalizedString
				/**
				 * {actor} couldn't escape!
				 */
				couldntEscape: (arg: { actor: unknown }) => LocalizedString
				/**
				 * {actor}'s buffs/debuffs have worn off.
				 */
				buffsWornOff: (arg: { actor: unknown }) => LocalizedString
				/**
				 * {actor} tried to use a skill, but skill system is not implemented yet!
				 */
				skillNotImplemented: (arg: { actor: unknown }) => LocalizedString
				/**
				 * {actor} tried to use an item, but item system is not implemented yet!
				 */
				itemNotImplemented: (arg: { actor: unknown }) => LocalizedString
			}
		}
		ui: {
			/**
			 * Health
			 */
			health: () => LocalizedString
			/**
			 * Mana
			 */
			mana: () => LocalizedString
			/**
			 * Stamina
			 */
			stamina: () => LocalizedString
			/**
			 * Level
			 */
			level: () => LocalizedString
			/**
			 * Experience
			 */
			experience: () => LocalizedString
			/**
			 * Inventory
			 */
			inventory: () => LocalizedString
			/**
			 * Equipment
			 */
			equipment: () => LocalizedString
			/**
			 * Skills
			 */
			skills: () => LocalizedString
			/**
			 * Stats
			 */
			stats: () => LocalizedString
			/**
			 * Settings
			 */
			settings: () => LocalizedString
			/**
			 * New Game
			 */
			newGame: () => LocalizedString
			/**
			 * Continue
			 */
			'continue': () => LocalizedString
			/**
			 * Load Game
			 */
			load: () => LocalizedString
			/**
			 * Save Game
			 */
			save: () => LocalizedString
			/**
			 * Quit
			 */
			quit: () => LocalizedString
			/**
			 * Loading...
			 */
			loading: () => LocalizedString
			/**
			 * Pause
			 */
			pause: () => LocalizedString
			/**
			 * Resume
			 */
			resume: () => LocalizedString
		}
		items: {
			/**
			 * Weapon
			 */
			weapon: () => LocalizedString
			/**
			 * Armor
			 */
			armor: () => LocalizedString
			/**
			 * Potion
			 */
			potion: () => LocalizedString
			/**
			 * Consumable
			 */
			consumable: () => LocalizedString
			/**
			 * Key
			 */
			key: () => LocalizedString
			/**
			 * Quest Item
			 */
			quest: () => LocalizedString
			/**
			 * Use
			 */
			use: () => LocalizedString
			/**
			 * Equip
			 */
			equip: () => LocalizedString
			/**
			 * Unequip
			 */
			unequip: () => LocalizedString
			/**
			 * Drop
			 */
			drop: () => LocalizedString
			/**
			 * Discard
			 */
			discard: () => LocalizedString
			/**
			 * Sell
			 */
			sell: () => LocalizedString
			/**
			 * Buy
			 */
			buy: () => LocalizedString
			/**
			 * Durability
			 */
			durability: () => LocalizedString
			/**
			 * Value
			 */
			value: () => LocalizedString
			/**
			 * Bonuses
			 */
			bonuses: () => LocalizedString
			rarity: {
				/**
				 * Common
				 */
				common: () => LocalizedString
				/**
				 * Uncommon
				 */
				uncommon: () => LocalizedString
				/**
				 * Rare
				 */
				rare: () => LocalizedString
				/**
				 * Epic
				 */
				epic: () => LocalizedString
				/**
				 * Legendary
				 */
				legendary: () => LocalizedString
			}
		}
		stats: {
			/**
			 * Strength
			 */
			strength: () => LocalizedString
			/**
			 * Dexterity
			 */
			dexterity: () => LocalizedString
			/**
			 * Intelligence
			 */
			intelligence: () => LocalizedString
			/**
			 * Vitality
			 */
			vitality: () => LocalizedString
			/**
			 * Luck
			 */
			luck: () => LocalizedString
			/**
			 * Attack
			 */
			attack: () => LocalizedString
			/**
			 * Defense
			 */
			defense: () => LocalizedString
			/**
			 * Magic Attack
			 */
			magicAttack: () => LocalizedString
			/**
			 * Magic Defense
			 */
			magicDefense: () => LocalizedString
			/**
			 * Speed
			 */
			speed: () => LocalizedString
			/**
			 * Critical Rate
			 */
			criticalRate: () => LocalizedString
			/**
			 * Evasion
			 */
			evasion: () => LocalizedString
		}
		messages: {
			/**
			 * Welcome to the Dungeon!
			 */
			welcome: () => LocalizedString
			/**
			 * Game Over
			 */
			gameOver: () => LocalizedString
			/**
			 * Game saved successfully
			 */
			gameSaved: () => LocalizedString
			/**
			 * Game loaded successfully
			 */
			gameLoaded: () => LocalizedString
			/**
			 * Obtained {item}
			 */
			itemObtained: (arg: { item: unknown }) => LocalizedString
			/**
			 * Used {item}
			 */
			itemUsed: (arg: { item: unknown }) => LocalizedString
			/**
			 * Cannot use that here
			 */
			cannotUseHere: () => LocalizedString
			/**
			 * Not enough gold
			 */
			notEnoughGold: () => LocalizedString
			/**
			 * Inventory is full
			 */
			inventoryFull: () => LocalizedString
			/**
			 * Are you sure you want to quit?
			 */
			confirmQuit: () => LocalizedString
			/**
			 * Yes
			 */
			yes: () => LocalizedString
			/**
			 * No
			 */
			no: () => LocalizedString
		}
	}
}

export type Formatters = {}
